Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "config.sh"
end