FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt-get update && apt install -y --no-install-recommends ansible git openjdk-8-jdk python3 pip rsync && pip install jmespath 

WORKDIR /opt/ansible
COPY config/*.yaml .

RUN ansible-galaxy install -n -p /opt/ansible -r requirements.yaml --ignore-errors && ansible-playbook nexus.yaml 

EXPOSE 8081

CMD sleep 5 && service nexus start && tail -f /dev/null