version: '3.8'

services:
  jenkins:
    container_name: jenkins-server
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    restart: always
    ports:
      - 80:8080
    networks:
      appNetwork:
        ipv4_address: 172.24.2.2
  
  nexus:
    container_name: nexus-server
    build:
      context: .
      dockerfile: Dockerfile.nexus
    ports:
      - 81:8081
    networks:
      appNetwork:
        ipv4_address: 172.24.2.1

networks:
  appNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"