version: '3.8'

services:
  jenkins:
    container_name: jenkins-server
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    restart: always
    ports:
      - 80:8080
    networks:
      - connection
  nexus:
    container_name: nexus-server
    build:
      context: .
      dockerfile: Dockerfile.nexus
    ports:
      - 81:8081
    networks:
      - connection

networks:
   connection:
    driver: bridge