---
- name : Update all VM's
  hosts: all
  become: true
  tasks:

  - name: Config hosts file 
    blockinfile:
      path  : /etc/hosts
      block : "192.168.56.10 master.puppet"

  - name: Download Puppet Repository
    yum:
      name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      state: present
      disable_gpg_check: true      

  - name: Stop the firewall service
    service: 
      name: firewalld
      state: stopped
      
- name: Configure master VM
  hosts: master
  become: true
  tasks:

  - name: Install puppetserver & git
    yum:
      name: "{{ item }}"  
    loop:
      - git
      - puppetserver

  - name: Puppet Configuration
    include_role :
      name : puppet
  
  - name: Config r10k stuff
    include_role :
      name : r10k
      tasks_from: main

- name: Configure slaves VM's
  hosts: slaves
  become: true
  tasks:

  - name: Install puppet-agent
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - puppet-agent

  - name: Config Slave's stuff
    include_role: 
      name: agent
      tasks_from: main

    

        
    





  
    





