- name: Create nexus symlink
  file:
    path: /opt/nexus/nexus
    state: link
    src: "{{ nexus_path.files[0]['path'] }}"
  when: nexus_path.matched > 0

- name: Copy environment file
  copy:
    src: ../files/nexus-server
    dest: /etc/default/nexus-server

- name: Copy systemd file
  copy:
    src: ../files/nexus.service
    dest: /etc/systemd/system/nexus.service

- name: Start Nexus service
  systemd:
    name: nexus
    enabled: yes
    state: started