FROM golang:1.16 AS BUILDER

WORKDIR /tmp

RUN git clone https://github.com/Fenikks/word-cloud-generator   

WORKDIR /tmp/word-cloud-generator
 
RUN GOOS=linux CGO_ENABLED=0 make build -f Makefile

#---------------------------------
FROM alpine:latest

RUN apk add --no-cache go 

WORKDIR /usr/lib/go/src    

COPY --from=BUILDER tmp/word-cloud-generator/artifacts/linux .

EXPOSE 8888

ENTRYPOINT ["./word-cloud-generator"]


