- name: Insert r10k config file
  file:
    path: /etc/puppetlabs/r10k
    state: directory

- name: Insert r10k & autosigh configs 
  template:
    dest: "{{ item.dest }}"
    src : "{{ item.src }}"
  loop:
    - {dest: "/etc/puppetlabs/r10k", src : 'roles/r10k/files/r10k.yaml'}
    - {dest: "/etc/puppetlabs/puppet", src : 'roles/r10k/files/autosign.conf'}
