Vagrant.configure("2") do |config|

  JENKINS_SERVER_IP='192.168.56.10'
  NEXUS_SERVER_IP='192.168.56.11'
  STAGING_SERVER_IP='192.168.56.12'
  PRODUCTION_SERVER_IP='192.168.56.13'

  config.vm.box = "generic/debian11"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins.vm"
    jenkins.vm.network "private_network", ip: JENKINS_SERVER_IP
    jenkins.vm.provision "ansible" do |ansible|
      ansible.playbook = "jenkins.yaml"
      ansible.host_vars = {
        "jenkins" => {"NEXUS_SERVER" => NEXUS_SERVER_IP,
                      "STAGING_SERVER"=>STAGING_SERVER_IP,
                      "PRODUCTION_SERVER"=>PRODUCTION_SERVER_IP,
                      "JENKINS_SERVER" => JENKINS_SERVER_IP,
        }
      }
    end
  end
  
  config.vm.define "nexus" do |nexus|
    nexus.vm.hostname = "nexus.vm"
    nexus.vm.network "private_network", ip: NEXUS_SERVER_IP
    nexus.vm.provision "ansible" do |ansible|
        ansible.playbook = "nexus.yaml"
        ansible.host_vars = {
          "nexus" => {"NEXUS_SERVER" => NEXUS_SERVER_IP,
          }
        }
    end    
  end

  config.vm.define "staging" do |staging|
    staging.vm.hostname = "staging.vm"
    staging.vm.network "private_network", ip: STAGING_SERVER_IP
    staging.vm.provision "ansible" do |ansible|
      ansible.playbook = "wordcloud.yaml"
      ansible.host_vars = {
          "jenkins" => {"NEXUS_SERVER" => NEXUS_SERVER_IP,
          }
        }
    end    
  end

  config.vm.define "production" do |production|
    production.vm.hostname = "production.vm"
    production.vm.network "private_network", ip: PRODUCTION_SERVER_IP
    production.vm.provision "ansible" do |ansible|
      ansible.playbook = "wordcloud.yaml"
      ansible.host_vars = {
          "jenkins" => {"NEXUS_SERVER" => NEXUS_SERVER_IP,
          }
        }
    end    
  end

end
