Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.hostname = "jenkins.vm"
  config.vm.network "private_network", ip: "192.168.56.10"
  
  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "jenkins.yaml"
    ansible.limit = "jenkins"
    ansible.inventory_path = 'inventory.ini'
  end

end
