---
- name: Config miniserver
  hosts: miniserver
  become: true
  tasks:

  - name: Download Puppet Repository
    yum:
      name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      state: present
      disable_gpg_check: true     
  
  - name: Stop the firewall service
    service: 
      name: firewalld
      state: stopped
  
  - name: Install puppet-agent
    yum:
      name: puppet-agent
      state: latest
  
  - include_vars: roles/agent/vars/agent-var.yaml

  - name: Config Slave's stuff
    include_role: 
      name: agent
      tasks_from: agent-config
      handlers_from: nginx-handler 
