Vagrant.configure("2") do |config|
  config.vm.define "master.puppet" do |master|
    master.vm.box = "generic/centos8s"
    master.vm.hostname ="master.puppet"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provision "shell", inline: <<-SHELL
    sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
    service sshd restart
    SHELL
  end

  config.vm.define "slave1.puppet" do |slave1|
    slave1.vm.box = "generic/centos8s"
    slave1.vm.hostname = "slave1.puppet"
    slave1.vm.network "private_network", ip: "192.168.56.11"
    slave1.vm.provision "shell", inline: <<-SHELL
    sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
    service sshd restart
    SHELL
  end

  config.vm.define "slave2.puppet" do |slave2|
    slave2.vm.box = "generic/centos8s"
    slave2.vm.hostname = "slave2.puppet"
    slave2.vm.network "private_network", ip: "192.168.56.12"
    slave2.vm.provision "shell", inline: <<-SHELL
    sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
    service sshd restart
    SHELL
  end
  
end

