- name: All Hosts Playbook
  hosts: vmgroup
  tasks:
  
  - name: Update all VM's
    become: true
    shell: sudo apt-get update -y 


- name: First VM
  hosts: firstvm
  become: true
  
  tasks:
  - name: Install Apache
    apt:
      name: apache2
  
  - name: Add config file
    template:
      src : "files/static.conf"
      dest: "/etc/apache2/sites-available/" 
      mode: '0777'
  
  - name: Config directory
    file:
      path  : /var/www/static
      mode  : '0777'
      state : directory

  - name: insert file      
    template:
      src : "files/index.html"
      dest: "/var/www/static/" 
      mode: '0777'
  
  - name: Update Apache configures
    shell: "{{ item }}"
    loop:
      - sudo a2ensite static.conf 
      - sudo a2dissite 000-default.conf
      - sudo systemctl restart apache2.service

- name: Second VM
  hosts: secondvm
  become: true
  tasks:
  - name: Install Apache & PHP
    apt:
      name: "{{ item }}"
    loop:
      - apache2
      - php
  
  - name: Add config file
    template:
      src : "files/dynamic.conf"
      dest: "/etc/apache2/sites-available/" 
      mode: '0777'
  
  - name: Config /var/www/... directory
    file:
      path  : /var/www/dynamic
      mode  : '0777'
      state : directory
  
  - name: insert file      
    template:
      src : "files/index.php"
      dest: "/var/www/static/" 
      mode: '0777'
  
  - name: Update Apache configures
    shell: "{{ item }}"
    loop:
      - sudo a2ensite dynamic.conf 
      - sudo a2dissite 000-default.conf
      - sudo systemctl restart apache2.service

- name: Proxy VM
  hosts: proxy
  become: true

  tasks:
  - name: install nginx
    apt:
      name: nginx
  
  - name: Config Proxy  
    template:
      src: "files/sites.com"
      dest: "/etc/nginx/sites-enabled/"
      mode: '0777'
  
  - name : Update Nginx configures
    shell: "{{ item }}"
    loop:
      - sudo nginx -t
      - systemctl restart nginx.service

  - name: Insert into hosts
    blockinfile:
      path: /etc/hosts
      block: "{{ hosts }}"
    vars:
      - hosts : |
                192.168.56.12 proxy.dynamic.com
                192.168.56.12 proxy.static.com
