- name: Proxy VM
  hosts: proxy
  become: true

  tasks:
  - name: install nginx
    apt:
      name: nginx
  
  - name: Config Proxy  
    template:
      src: "files/sites.com"
      dest: "/etc/nginx/sites-enabled/"
      mode: '0777'
  
  - name : Update Nginx configures
    shell: "{{ item }}"
    loop:
      - sudo nginx -t
      - systemctl restart nginx.service

  # - name: Insert into hosts
  #   blockinfile:
  #     path: /etc/hosts
  #     block: "{{ hosts }}"
  #   vars:
  #     - hosts : |
  #               192.168.56.12 192.168.56.12/dy
