Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "allvms.yaml"
  end
  
  config.vm.define "firstvm" do |firstvm|
    firstvm.vm.network "private_network", ip: "192.168.56.10"
    firstvm.vm.provision "ansible" do |ansible|
      ansible.playbook = "firstvm.yaml"
    end
  end

  config.vm.define "secondvm" do |secondvm|
    secondvm.vm.network "private_network", ip: "192.168.56.11"
    secondvm.vm.provision "ansible" do |ansible|
      ansible.playbook = "secondvm.yaml"
    end
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.network "private_network", ip: "192.168.56.12"
    proxy.vm.provision "ansible" do |ansible|
      ansible.playbook = "proxyvm.yaml"
    end
  end

end
