

Vagrant.configure("2") do |config|

  config.vm.define "first" do |first|
    first.vm.box = "ubuntu/xenial64"
    first.vm.network "public_network",  use_dhcp_assigned_default_route: true
    first.vm.provision "shell", path: "configvm1.sh"
  end

  config.vm.define "second" do |second|
    second.vm.box = "ubuntu/xenial64"
    second.vm.network "public_network",  use_dhcp_assigned_default_route: true
    second.vm.provision "shell", path: "configvm2.sh"
  end

end

