- name: Create a jenkins job 
  community.general.jenkins_job:
    config: "{{ lookup('file', '../files/goBuilder.xml') }}"
    name: goBuilder
    user: admin
    password: admin
    url: http://192.168.56.10:8080
    state: present  
 