- name: Create a jenkins job 
  community.general.jenkins_job:
    config: "{{ lookup('file', '../files/goBuilder.xml') }}"
    name: goBuilder
    user: admin
    password: admin
    url: http://{{ JENKINS_SERVER }}:8080
    state: present  
  

