Vagrant.configure("2") do |config|

  config.vm.define "first" do |first|
    first.vm.box = "generic/debian11"
    first.vm.network "private_network", ip: "192.168.10.193"
    first.vm.provision "shell", path: "configvm1.sh"
  end

  config.vm.define "second" do |second|
    second.vm.box = "generic/debian11"
    second.vm.network "private_network", ip: "192.168.60.10"
    second.vm.provision "shell", path: "configvm2.sh"
  end

end

