---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wcg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://defau1t17.github.io/devops-hometasks/'
    targetRevision: 1.0.0
    chart: wordcloudchart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
