- name: Reload daemon
  shell: systemctl daemon-reload

- name: Start Up Jenkins Service
  service:
    name: jenkins
    state: started
    
- name: Restart Jenkins Service
  service:
    name: jenkins
    state: restarted


