- name: Create Groovy dir
  file:
    path  : "{{ item }}"
    mode  : '0777'
    state : directory
    owner: jenkins
    group: jenkins
  loop:
    - /var/lib/jenkins/casc_configs/
    - /var/lib/jenkins/init.groovy.d/