- name: Config Jenkins Environment
  replace:
    regexp: "{{ item.reg }}"
    replace: "{{ item.replace }}"
    path: /lib/systemd/system/jenkins.service
  loop:
    - {reg: 'Environment="JAVA_OPTS=-Djava.awt.headless=true"' , replace : 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Dcasc.jenkins.config=${JENKINS_HOME}/casc_configs -Djenkins.install.runSetupWizard=false"'}
    - {reg: '#TimeoutStartSec=90' , replace : 'TimeoutStartSec=3600'}
  notify:
    - Reload daemon
    - Restart Jenkins Service

- name: "Flush handlers"
  meta: flush_handlers
