- name: Load Groovy Scripts at VM
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: '../files/01-admin-user.groovy', dest: '/var/lib/jenkins/init.groovy.d/'}
    - {src: '../files/02_plugins.groovy', dest: '/var/lib/jenkins/init.groovy.d/'}
    - {src: '../files/credentials.yaml', dest: '/var/lib/jenkins/casc_configs/'} 