- name: Install Java & Jenkins & Pip & JQ 
  apt: 
    name: "{{ item }}"
    state: present
  loop:
    - openjdk-11-jdk
    - jenkins
    - pip
  notify:
    - Start Up Jenkins Service

- name: Install Python For Jenkins
  pip:
    name: python-jenkins