jenkins:
  systemMessage: 'This is my first Jenkins Job'

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope:    GLOBAL
          id:       cread
          username: vagrant
          password: vagrant

tool:
  go:
    installations:
      - name: "go_lang"
        properties:
          - installSource:
              installers:
                - golangInstaller:
                    id: "1.20"