jenkins:
  systemMessage: 'This is my first Jenkins Job'

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope:    GLOBAL
          id:       vagrant
          username: vagrant
          password: vagrant
    - credentials:
      - usernamePassword:
          scope:    GLOBAL
          id:       jenkins
          username: jenkins
          password: jenkins


tool:
  go:
    installations:
      - name: "go_lang"
        properties:
          - installSource:
              installers:
                - golangInstaller:
                    id: "1.20"