---
- name: Test play
  hosts: all
  tasks:
  - name : Update system
    become: yes
    command: sudo apt-get update

  - name: Install Apache
    become : true
    apt:
      name  : "{{ item }}"
    loop:
      - apache2
      - php

  - name: Create /var/www/... dirs and index files
    become: true
    ansible.builtin.file:
      path  : "{{ item.path }}"
      state : "{{ item.state }}"
      owner : "{{ item.owner }}"
      mode  : "{{ item.mode }}"
    loop:
        - { path: /var/www/static, state: directory, owner: root, mode: '0777'} 
        - { path: /var/www/dynamic, state: directory , owner: root, mode: '0777' }
  - name : Add templaytes
    become : true
    template:
      src: "files/{{item.file}}"
      dest : "{{item.dest}}"
    loop:
      - {file : index.html, dest: /var/www/static/}
      - {file : index.php, dest: /var/www/dynamic/}
      - {file : static.conf, dest: /etc/apache2/sites-available/}
      - {file : dynamic.conf, dest: /etc/apache2/sites-available/}

  - name: Inser configurations and pages content
    become : true
    ansible.builtin.blockinfile  :
      path   :  /etc/apache2/ports.conf 
      block  : "{{ mainports }}"
    vars:
        mainports: |
          Listen 8080
          Listen 8081  

  - name: Apply configs
    become : true
    shell : "{{ item }}" 
    loop:
      - sudo a2ensite dynamic.conf 
      - sudo a2ensite static.conf 
      - sudo a2dissite 000-default.conf
      - sudo systemctl restart apache2.service


