---
- name: Test play
  hosts: all
  tasks:
  - name : Update system
    become: yes
    command: sudo apt-get update

  - name: Install Apache
    become : true
    apt:
      name  : "{{ item }}"
    loop:
      - apache2
      - php

  - name: Create /var/www/... dirs and index files
    become: true
    ansible.builtin.file:
      path  : "{{ item.path }}"
      state : "{{ item.state }}"
      owner : "{{ item.owner }}"
      mode  : "{{ item.mode }}"
    loop:
        - { path: /var/www/static, state: directory, owner: root, mode: '0777'} 
        - { path: /var/www/dynamic, state: directory , owner: root, mode: '0777' }
        - { path : /var/www/static/index.html , state: touch , owner: root, mode: '0777'}
        - { path : /var/www/dynamic/index.php ,state: touch , owner: root, mode: '0777'}
        - { path: /etc/apache2/sites-available/static.conf, state: touch , owner: root, mode: '0777'}
        - { path: /etc/apache2/sites-available/dynamic.conf, state: touch , owner: root, mode: '0777'}

  - name: Inser configurations and pages content
    become : true
    ansible.builtin.blockinfile  :
      path    : "{{ item.path }}"
      block  : "{{ item.line }}"
    loop:
      - { path: /var/www/static/index.html, line : "Hello world!" }
      - { path: /var/www/dynamic/index.php, line : "<?php phpinfo(); ?>" }
      - { path: /etc/apache2/sites-available/static.conf, line : "{{ firsthost }}"}
      - { path: /etc/apache2/sites-available/dynamic.conf, line : "{{ secondhost }}"}
      - { path: /etc/apache2/ports.conf, line : "{{ mainports }}"}
    vars:
      firsthost: |
        <VirtualHost *:8080>
        DocumentRoot /var/www/static
        ServerName localhost
        <Directory /var/www/static>
        Options FollowSymlinks
        AllowOverride All
        Require all granted
        </Directory>
        </VirtualHost>
      secondhost: |
        <VirtualHost *:8081>
        DocumentRoot /var/www/dynamic
        ServerName localhost
        <Directory /var/www/dynamic>
        Options FollowSymlinks
        AllowOverride All
        Require all granted
        </Directory>
        </VirtualHost>
      mainports: |
        Listen 8080
        Listen 8081              

  - name: Apply configs
    become : true
    shell : "{{ item }}" 
    loop:
      - sudo a2ensite dynamic.conf 
      - sudo a2ensite static.conf 
      - sudo a2dissite 000-default.conf
      - sudo systemctl restart apache2.service


