name: Deploy a Docker.multi Container 
run-name: Docker.multi
on:
  workflow_dispatch
env:
  IMAGE_NAME: wcg
  RESOURSE: ghcr.io
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install docker git -y
      - run: git clone https://github.com/defau1t17/devops-hometasks.git
      - run: docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} . -f devops-hometasks/07-docker/Dockerfile.multi
      - run: echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner.toLowerCase }} --password-stdin
      - run: docker tag ${{env.IMAGE_NAME}}:latest ${{env.RESOURSE}}/${{ github.repository_owner.toLowerCase }}/${{env.IMAGE_NAME}}:latest
      - run: docker tag ${{env.IMAGE_NAME}}:${{ github.sha }} ${{env.RESOURSE}}/${{ github.repository_owner.toLowerCase }}/${{env.IMAGE_NAME}}:${{ github.sha }}
      - run: docker image push ${{env.RESOURSE}}/${{ github.repository_owner.toLowerCase }}/${{env.IMAGE_NAME}}:latest
      - run: docker image push ${{env.RESOURSE}}/${{ github.repository_owner.toLowerCase }}/${{env.IMAGE_NAME}}:${{ github.sha }}
