name: Deploy a Docker.multi Container 
run-name: Docker.multi
on:
  workflow_dispatch
  
jobs:
  test:
    name: Say Hello world
    runs-on: ubuntu-18.04
    steps:
      - name: Pring 
        run: echo 'Hello World'
