name: Deploy a Docker.multi Container 
run-name: Docker.multi
on:
  workflow_dispatch

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: firehed/multistage-docker-build-action@v1
        id: build
        with:
          dockerfile: 07-docker/Dockerfile.multi
          repository: ghcr.io/firehed/actions
          stages: BUILD
          testenv-stage: testenv
          server-stage: server
          build-args: arg1=val1, arg2=val2
    

