name: Deploy a Docker.multi Container 
run-name: Docker.multi
on:
  workflow_dispatch

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v5.1.0
      with:
        context: ../../07-docker
        file:  "Dockerfile.multi"
        tags: wcg:latest
        load: true
        push: false
    

