name: Deploy a Docker.multi Container 
run-name: Docker.multi
on:
  workflow_dispatch

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
    - uses: bskiefer/docker_buildx@v1.4
      with:
        tag: latest
        imageName: wcg 
        dockerFile: "Dockerfile.multi"
        publish: false
        
    

