name: Deploy a Docker.multi Container 
run-name: Docker.multi
on:
  workflow_dispatch

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install docker -y
      - run:  docker build -t wcg:latest ../../07-Docker/ -f Dockerfile.multi
      
    

