name: Deploy a Docker.multi Container 
run-name: Docker.multi
on:
  workflow_dispatch
env:
  IMAGE_NAME: wcg
  RESOURSE: ghcr.io
  VERSION_TAG: 0.0.1
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}
      - run: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null ; sudo apt-get install apt-transport-https -y
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list;
      - run: sudo apt update && sudo apt install docker git helm -y
      - run: git clone https://github.com/defau1t17/devops-hometasks.git
      - run: docker build -t $IMAGE_NAME:${{ env.VERSION_TAG }} . -f devops-hometasks/07-docker/Dockerfile.multi
      - run: echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u ${{ steps.string.outputs.lowercase }} --password-stdin
      - run: docker tag ${{env.IMAGE_NAME}}:${{ env.VERSION_TAG }} ${{env.RESOURSE}}/${{ steps.string.outputs.lowercase }}/${{env.IMAGE_NAME}}:${{ env.VERSION_TAG }}
      - run: docker image push ${{env.RESOURSE}}/${{ steps.string.outputs.lowercase }}/${{env.IMAGE_NAME}}:${{ env.VERSION_TAG }}
      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          release_branches: main
          custom_tag : ${{ env.VERSION_TAG }}
      - run: helm lint 12-helm/ 
      - name: Replace version
        run: |
          sed -i 's/imageVersion: .*/imageVersion: ${{ env.VERSION_TAG }}/' 12-helm/values.yaml
      - run: helm package 12 ; mv *.tgz docs/ ; helm repo index docs --url https://${{ steps.string.outputs.lowercase }}.github.io/devops-hometasks/
      - run: git add -i ; git commit -av ; git push origin main ;
