name: Deploy a Docker.multi Container 
run-name: Docker.multi
on:
  workflow_dispatch

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: Firehed/multistage-docker-build-action@v1.7.0
        with:
          file:  "07-docker/Dockerfile.multi"
          tags: wcg:latest
          load: true
          push: false
          platforms: ghcr.io
          
